### ISSUE TITLE
in-place constructor for RwLock ?

### ISSUE THREAD

**Issue by Clonkk** [planetis-m/sync#23]
Experimenting with RwLock, it seems (or maybe I haven't figured it out ?) impossible to create a RwLock in place to be used within a container (e.g table in my example).

The goal is manage lock for a list of ressources (identified by a URI) using a Table; since `=sink` is defined as {.error.} (perfectly normal for a lock)  : 

```nim

var lockers : Table[string, RwLock]

proc beginRead(uri: string)  =  
  if not lockers.hasKey(uri):
    var lock: RwLock
    lock.init()
    lockers[uri] = lock # can't compile because `=sink` does not exists.
  lockers[uri].beginRead()
  ```

**Comment by planetis-m** [comment]
Yeah sink is an error for Locks, which is what RwLock internally uses. Moreover at the time assignment for Locks was broken (Nim bug) but it's now fixed. I don't know what to suggest in your case, sorry

**Comment by planetis-m** [comment]
Perhaps tables.withKey can work

**Comment by Clonkk** [comment]
I found a workaround by using importcpp on placement new with a Table[string, ref RwLock], but it's kinda ugly I was hoping there'd be a better solution

**Comment by planetis-m** [comment]
An idea is to include tables and write a template similar to withValue but for the opposite case.

**Comment by Clonkk** [comment]
Yeah that'd probably work but to be honest, I'd rather not having to modify (I've found include to be particularly dangerous) the stdlib as my code would break with stdlib change. 

For reference in case anyone has a similar issue this is how I solved it : 

```nim
proc initRwLock*(): RwLock {.exportc: "initRwLock".} =
  result.init()

proc placeNew*[T](adr: ptr T) {.importcpp: "new(#) '*1(initRwLock())".}

template emplace*(s: var Table[string, ref RwLock], key: string): untyped =
  let adr = s[key][].addr
  var loc = cast[ptr RwLock](adr)
  placeNew[RwLock](loc)
  
# Then you can do : 
proc main() =
  var locker : Table[string, ref RwLock]
  locker[key] = new(RwLock)
  locker.emplace(key)

```

Not the prettiest, but it works
